### 1. CREATE COURSE
POST localhost:8080/course/create
Content-Type: application/json

{
  "name": "Kotlin",
  "price": 1500000.0,
  "duration": 7
}

### 1. CREATE COURSE ALL
POST localhost:8080/course/create/all
Content-Type: application/json

[
  {
    "name": "PHP",
    "price": 80.0,
    "duration": 9
  },
  {
    "name": "Java",
    "price": 100.0,
    "duration": 7
  },
  {
    "name": "C",
    "price": 60.0,
    "duration": 7
  },
  {
    "name": "C++",
    "price": 70.0,
    "duration": 7
  },
  {
    "name": ".Net",
    "price": 100.0,
    "duration": 7
  },
  {
    "name": "Python",
    "price": 90.0,
    "duration": 8
  },
  {
    "name": "JavaScript",
    "price": 110.0,
    "duration": 8
  },
  {
    "name": "Swift",
    "price": 120.0,
    "duration": 7
  },
  {
    "name": "Go",
    "price": 80.0,
    "duration": 6
  },
  {
    "name": "QA",
    "price": 50.0,
    "duration": 4
  },
  {
    "name": "Ruby",
    "price": 85.0,
    "duration": 6
  },
  {
    "name": "Flutter",
    "price": 90.0,
    "duration": 9
  },
  {
    "name": "Kotlin",
    "price": 110.0,
    "duration": 7
  },
  {
    "name": "PostgreSQL",
    "price": 750.0,
    "duration": 5
  },
  {
    "name": "ReactJS",
    "price": 80.0,
    "duration": 6
  },
  {
    "name": "Angular",
    "price": 80.0,
    "duration": 6
  },
  {
    "name": "Oracle",
    "price": 100.0,
    "duration": 6
  }
]

### 2. GET BY id
GET localhost:8080/course/2

### 3. GET ALL COURSE
GET localhost:8080/course/all

### 4. UPDATE by id
PUT localhost:8080/course/1
Content-Type: application/json

{
  "price": 80.0
}

### 5. DELETE BY id
DELETE localhost:8080/course/3

### 6. GET BY name
GET localhost:8080/course/name?name=Java

### 6. GET BY price
GET localhost:8080/course/price?price=1500000

### 6. GET BY duration
GET localhost:8080/course/duration?duration=5

### 7. GET BY beetwen date
GET localhost:8080/course/get_price_between?from=70&to=100

### 8. GET BY beetwen date
GET localhost:8080/course/get_between_date?startDate=2023-07-01&endDate=2023-07-31

### 8. GET BY created_date
GET localhost:8080/course/created_date?created_date=2023-07-05

### 9. GET student pagenation
GET localhost:8080/course/pagination?page=0&size=3

### 10. GET student pagenation by created_date
GET localhost:8080/course/pagination/sort_by_created_date?page=0&size=3

### 11. GET student pagenation by price
GET localhost:8080/course/pagination/by_price?page=0&size=3&price=80

### 12. GET student pagenation by price between
GET localhost:8080/course/pagination/by_price_between?page=0&size=5&from=90&to=100

### 13. Filter
POST localhost:8080/course/filter
Content-Type: application/json

{
  "price": 80,
  "duration": 9
}

