### CREATE STUDENT
POST localhost:8080/student/create
Content-Type: application/json

{
  "name": "Hasan",
  "surname": "Hasanov",
  "level": 2,
  "age": 21,
  "gender": "MALE",
  "phone": "111"
}


### CREATE STUDENT ALL
POST localhost:8080/student/create/all
Content-Type: application/json

[
  {
    "name": "Vali",
    "surname": "Umarov",
    "level": 1,
    "age": 23,
    "gender": "MALE",
    "phone": "111111"
  },
  {
    "name": "Lola",
    "surname": "Aliyeva",
    "level": 4,
    "age": 24,
    "gender": "FEMALE",
    "phone": "222222"
  },
  {
    "name": "Majid",
    "surname": "Sobirov",
    "level": 3,
    "age": 22,
    "gender": "MALE",
    "phone": "333333"
  },
  {
    "name": "Hamdan",
    "surname": "Azizov",
    "level": 2,
    "age": 25,
    "gender": "MALE",
    "phone": "444444"
  },
  {
    "name": "Samandar",
    "surname": "Yusupov",
    "level": 4,
    "age": 23,
    "gender": "MALE",
    "phone": "555555"
  },
  {
    "name": "Yusuf",
    "surname": "Azimov",
    "level": 2,
    "age": 27,
    "gender": "MALE",
    "phone": "666666"
  },
  {
    "name": "Habiba",
    "surname": "Valiyeva",
    "level": 4,
    "age": 30,
    "gender": "FEMALE",
    "phone": "777777"
  },
  {
    "name": "Nigora",
    "surname": "Qamarova",
    "level": 2,
    "age": 22,
    "gender": "FEMALE",
    "phone": "888888"
  },
  {
    "name": "Qamar",
    "surname": "Ibrohimov",
    "level": 4,
    "age": 26,
    "gender": "MALE",
    "phone": "999999"
  }
]


### GET ALL STUDENT
GET localhost:8080/student/all

### GET BY id
GET localhost:8080/student/

### GET BY phone
GET localhost:8080/student/phone?phone=123456

### GET BY name
GET localhost:8080/student/name?name=Vali

### GET BY surname
GET localhost:8080/student/surname?surname=Aliyev

### GET BY age
GET localhost:8080/student/age?age=

### GET BY level
GET localhost:8080/student/level?level=

### GET BY gender
GET localhost:8080/student/gender?gender=

### GET BY created_date
GET localhost:8080/student/created_date?created_date=2023-07-05

### GET BY beetwen date
GET localhost:8080/student/date-range?startDate=2023-07-01&endDate=2023-07-31

### GET student pagenation
GET localhost:8080/student/pagination?page=0&size=3

### GET student pagenation by level
GET localhost:8080/student/pagination/by-level?page=0&size=3&level=2

### GET student pagenation by gender
GET localhost:8080/student/pagination/by-gender?page=0&size=3&gender=FEMALE




### DELETE ALL
DELETE localhost:8080/student/delete/all

### DELETE BY id
DELETE localhost:8080/student/4

### UPDATE id
PUT localhost:8080/student/10
Content-Type: application/json

{
  "name": "Hasan",
  "surname": "Hasanov"
}
